config/routes.rb
Crumblr1::Application.routes.draw do
  
  resources :listings

  get "about" => 'pages#about'

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Job Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Job Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:job_title, :job_location, :job_description, :job_email, :company_name, :company_website, :company_email, :company_description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Work in analytics</p>

app/views/layouts/_header.html.erb
<div class="page-header">
			<ul class="nav nav-pills pull-right">
				<li><%= link_to "Home", "/" %></li>
				<li><%= link_to "About", "/about" %></li>
			</ul>
			<h3>Work in Analytics</h3>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Work In Analytics</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
			<%= yield %>
		<%= render 'layouts/footer' %>
	</div>


</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Your job listing will remain for 45 days. After 45 days your job listing will expire and be removed.</h4>
  <br/>
  <h3><b>1. Tell us about the position.</b></h3>
  <br/>

  <div class="form-group">
    <%= f.label "job title" %>
    <%= f.text_field :job_title, class: "form-control", autofocus: true, placeholder: "E.g Analytics Manager" %>
  </div>
  <div class="form-group">
    <%= f.label "Location" %>
    <%= f.text_field :job_location, class: "form-control", placeholder: "E.g London" %>
  </div>
  <div class="form-group">
    <%= f.label "Enter job description" %>
    <%= f.text_area :job_description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "How does the candidate apply for this position" %>
    <%= f.text_field :job_email, class: "form-control", placeholder: "E.g Send a C.V to admin@yourcompany.com" %>
  </div>

  <h3><b>2. Tell us about your company or recruitment agency</b></h3>
  <br/>

  <div class="form-group">
    <%= f.label "Your Company Name" %>
    <%= f.text_field :company_name, class: "form-control", placeholder: "E.g Google" %>
  </div>
  <div class="form-group">
    <%= f.label "Company Website" %><br>
    <%= f.text_field :company_website, class: "form-control", placeholder: "www.google.com" %>
  </div>

  <div class="form-group">
    <%= f.label "Tell Us About Your Business 25-30 chars max" %>
    <%= f.text_field :company_website, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label "Email address to send the reciept to" %><br>
    <%= f.text_field :company_email, class: "form-control", placeholder: "E.g John@google.com" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="row">
    <div class="center">
        <h1>Find a Great Job in the Web Analytics Industry</h1>
          <h3>We only show open analytics jobs to make your search easy</h3>
          <h3>Follow us on Twitter <span class="emphasis">@WorkinAnalytics</span> </h3>
          <br>
           <%= link_to "Post a job Today: $169 for 45 days", new_listing_path , class: "btn btn-danger btn-lg", data: { no_turbolink: true } %>
    </div>
</div>
<br/>


  <table class="table table-hover">
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to listing.job_title, listing %></td>
        <td><%= listing.job_location %></td>
        <td><%= listing.company_name %></td>
        <td><%= listing.created_at.strftime("%B %-d, %Y") %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job title:</strong>
  <%= @listing.job_title %>
</p>

<p>
  <strong>Job location:</strong>
  <%= @listing.job_location %>
</p>

<p>
  <strong>Job description:</strong>
  <%= @listing.job_description %>
</p>

<p>
  <strong>Job email:</strong>
  <%= @listing.job_email %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @listing.company_name %>
</p>

<p>
  <strong>Company website:</strong>
  <%= @listing.company_website %>
</p>

<p>
  <strong>Company email:</strong>
  <%= @listing.company_email %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/pages/about.html.erb
<h1>About</h1>

<p>lets connect @neilp666</p>

app/views/pages/welcome.html.erb
<h1>Find A Great Job in the Web Analytics Industry</h1>

<h4>
	We Only Show Open Analytics jobs to make your search easy.Follow us on Twitter @WorkinAnalytics
</h4>